### ISSUE TITLE
Elements logged to console are barely legible in dark themes

### ISSUE THREAD

**Issue by DisasterMan78** [micjamking/devtools-author#101]
The dark colours used when elements are logged to console (e.g. `document.getElementById('{{elementId}}');` ) are very dark and do not contrast well enough with the background colour to be legible.

![image](https://cloud.githubusercontent.com/assets/2079401/12746953/375d7362-c999-11e5-84c1-a0c9343d88ec.png)

**Comment by micjamking** [comment]
@DisasterMan78 thank you for breaking this out as a separate issue; will try to address this as soon as I can.

**Comment by micjamking** [comment]
This should be resolved in release v0.5.8

![screen shot 2016-02-03 at 12 14 03 am](https://cloud.githubusercontent.com/assets/651702/12779313/5fd9e43e-ca0b-11e5-9127-30413e94b89a.png)
