### ISSUE TITLE
cursor is missing on element attribute

### ISSUE THREAD

**Issue by whatifhappen** [micjamking/devtools-author#107]
Hi, when I clicked on the element attribute, the cursor is gone,
![image 5](https://cloud.githubusercontent.com/assets/4222249/12814243/826cd614-cb78-11e5-8a0c-ed9e3a8638a2.png)
 any idea how to fixed that?

**Comment by micjamking** [comment]
Hey @whatifhappen, thanks for bringing this to my attention! This issue should be resolved in v0.5.10 a6ef221

![cursor](https://cloud.githubusercontent.com/assets/651702/12829187/d8c2fba2-cb2c-11e5-96b7-4fa8aab0c389.gif)

**Comment by whatifhappen** [comment]
it's working, thanks
