### ISSUE TITLE
Improve console.table readability

### ISSUE THREAD

**Issue by PEM--** [micjamking/devtools-author#124]
When using `console.table` with dark theme, its `table`'s `background-color` should be adapted for having a better readability:

```js
console.table({test1: [1, 2, 3, 4]})
```

![capture d ecran 2016-02-14 a 09 31 20](https://cloud.githubusercontent.com/assets/227831/13032729/5d4e3ec6-d2fe-11e5-865f-42ffe6f13509.png)

PS: Amazing work and thanks for sharing it :star:

**Comment by micjamking** [comment]
Hey @PEM-- , thanks again for bringing this issue to my attention! 

The `console.table` readability issues have been resolved in release [v0.6.2](https://github.com/micjamking/devtools-author/releases/tag/v0.6.2)

**Dark Theme: Monokai**
![screen shot 2016-02-14 at 2 27 00 pm](https://cloud.githubusercontent.com/assets/651702/13037576/2fdf84ac-d328-11e5-919c-7dcca0871f78.png)

**Light Theme: 3024**
![screen shot 2016-02-14 at 2 28 44 pm](https://cloud.githubusercontent.com/assets/651702/13037575/2fdccdde-d328-11e5-9be0-70cc9fb9993f.png)

Let me know if you have any other issues or other concerns. 

Mahalo! :v:

**Comment by PEM--** [comment]
I'm unfortunately too busy on customer's duty for proposing you a PR on this. Thanks @micjamking. You rock!  :clap:
