### ISSUE TITLE
How do I change themes?

### ISSUE THREAD

**Issue by sunilw** [micjamking/devtools-author#126]
I'm uncertain whether this counts as an issue or not. But I can't figure out how to switch from the default theme.

Is there a settings UI for devtools-author? How do I find it?

**Comment by micjamking** [comment]
@sunilw If you have followed all of the instructions listed in the [README.md#Usage](https://github.com/micjamking/devtools-author#usage) section, then you should see an additional 'Author Settings' panel available in DevTools. You can change the themes from this panel (see below).

![screen shot 2016-02-17 at 1 08 53 am](https://cloud.githubusercontent.com/assets/651702/13107720/0e36a58c-d513-11e5-955b-395d7c3afeab.png)

**Comment by sunilw** [comment]
I didn't think to look there. 

It wasn't obvious to my eye. Probably because I've got a few devtools options and extensions enabled that crowd that part of the UI.

Thank you.
