### ISSUE TITLE
No option for Experiments in Chrome 48.0.2564.116 (64-bit)

### ISSUE THREAD

**Issue by alistaircom** [micjamking/devtools-author#132]
Using Chrome 48.0.2564.116 (64-bit) on Mac OSX 10.10.5 (Yosemite)

I have added the extension from the Chrome Web store. I then tried to follow the instructions:

    Open DevTools (cmd + opt + I); Settings > Experiments > check Allow custom UI themes.

I don't see the option for Experiments anywhere.  Is there something I have to enable elsewhere in order to see the Experiments option?

Screenshots:
![screenshot 2016-02-24 10 35 03](https://cloud.githubusercontent.com/assets/855160/13296618/45e7e4a2-dae3-11e5-8f7c-d6f7e17f037f.png)

![screenshot 2016-02-24 10 35 58](https://cloud.githubusercontent.com/assets/855160/13296628/4f8aaca6-dae3-11e5-9cce-91c08c59fc6a.png)

**Comment by alistaircom** [comment]
Got it.  I needed to enable: 
chrome://flags/#enable-devtools-experiments

I didn't see that in the Chrome Web Store instructions, instead just following the instructions here on Github.  

Perhaps add that into the README.

**Comment by micjamking** [comment]
@alistaircom glad you got it resolved! Let me know if you experience any other issues.
