### ISSUE TITLE
Overall theme not working with Version 54.0.2840.59 (64-bit)

### ISSUE THREAD

**Issue by davidpanzarella** [micjamking/devtools-author#149]
Code styles seem to work fine, but all the other settings for inspector, tabs, etc are default or dark theme that ships with Chrome.

**Comment by nasyrov** [comment]
Can confirm that, please check the attachment.
![screen shot 2016-10-20 at 16 46 56](https://cloud.githubusercontent.com/assets/1330477/19567240/e59bef44-96e4-11e6-8b01-10579ea7ac56.png)

**Comment by davidpanzarella** [comment]
@micjamking I guess this is no longer maintained?

**Comment by andreylysenko** [comment]
Same story on Chrome for Mac ver. 54.0.2840.98
![dt1](https://cloud.githubusercontent.com/assets/1424450/20471880/bfcc5398-afbd-11e6-84a0-b81530d786bb.jpg)
