### ISSUE TITLE
how to change theme?

### ISSUE THREAD

**Issue by olets** [micjamking/devtools-author#159]
I can't figure how to switch themes (macOS, but I'm not finding documentation for any OS), and can't find the "25+ editor themes" listed on http://mikeking.io/devtools-author/. Help?

Edit: I've found the themes. Still can't tell how to select one. On macOS, Chrome 60:

```
~/Library/Application Support/Google/Chrome/Profile1/Extensions/egfhcfdfnajldliefpdoaojgahefjhhi/0.6.6_0/dist/styles/themes
```

**Comment by colinhowells** [comment]
Once enabled

    Enable Developer Tools experiments in chrome://flags/#enable-devtools-experiments. Restart Chrome for flags to take effect.
    Open DevTools (cmd + opt + I); Settings > Experiments > check Allow custom UI themes.

then you've got an additional menu - themes are in the pulldown (Material Dark for me):

<img width="838" alt="schemes" src="https://user-images.githubusercontent.com/2035314/29473382-879a878c-840c-11e7-9793-e68641347f16.png">

**Comment by olets** [comment]
Sweet, completely missed that menu! 🙌
