### ISSUE TITLE
Not working on chrome 63

### ISSUE THREAD

**Issue by aneeskodappana** [micjamking/devtools-author#167]
chrome version -  63.0.3239.84

**Comment by ntnbst** [comment]
guess they have no longer support.

**Comment by arsari** [comment]
not working either on this version of chrome, Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by marcustisater** [comment]
Sucks! I really liked this plugin. Let me know if there is anything to help out with.

**Comment by mixj93** [comment]
Me too

**Comment by ronilaukkarinen** [comment]
Yeah, 65.0.3322.3 (Official Build) dev (64-bit) here, not working ☹️ bummer.

**Comment by aocneanu** [comment]
I chilled because I used it only for changing the console font size, and the other day I pressed by mistake `cmd +` while I was focusing the console and *baam*, the font increased. (ctrl for win)
