### ISSUE TITLE
Support additional font families

### ISSUE THREAD

**Issue by micjamking** [micjamking/devtools-author#30]
Font's are loaded directly from the users computer, so the extension is technically capable of supporting any font that's currently enabled on the users system.

However, for maximum legibility and consistency, it's preferred to constrain the set of typefaces to monospace fonts created for pre-formatted text/code display. 

For now, we support `Hack`, `Source Code Pro` and `Droid Sans Mono` and the default, system monospace font.

**Comment by cowboy** [comment]
Please add support for the excellent, free monospace M+ Fonts!

* M+ M Type-1
* M+ M Type-2
* M+ MN Type-1

https://mplus-fonts.osdn.jp/design.html
