### ISSUE TITLE
Wrapped text on elements panel is difficult to read

### ISSUE THREAD

**Issue by epilande** [micjamking/devtools-author#66]
Awesome job on the elements panel!

With a light theme, wrapped text is a bit hard to read (see attached screenshot).
The selected element text color is white, making it hard to read with a light background.

A possible fix is to remove line 866 `height: 22px !important;` from `/app/styles/modules/_common-styles.scss`  

![screen shot 2016-01-07 at 1 43 43 am](https://cloud.githubusercontent.com/assets/3210082/12170030/8828383a-b4e1-11e5-990b-38bfa621d71c.png)

**Comment by micjamking** [comment]
@epilande: just saw this, thanks for catching that! Yes, that was suppose to be a min-height for the selection. Just pushed up a fix and updated the plugin, you should see the changes in an hour or so.
