### ISSUE TITLE
Theme name with line-break prevents select UI

### ISSUE THREAD

**Issue by taylorkmho** [micjamking/devtools-author#70]
![screen shot 2016-01-25 at 9 32 53 am](https://cloud.githubusercontent.com/assets/5141111/12561947/a12fe580-c346-11e5-85e5-db444eabfc8a.png)

Just adding because I know more eyes = a good thing. I'm looking into the codebase to see if I can figure out a way to fix and pull request. Cool project, bruh!

**Comment by micjamking** [comment]
@taylorkmho Good looking out sir! This is probably related to the fixed width I have on the panel `.container` class; at the moment I'm not really using any media queries to make the panel responsive ( :astonished: I know). 

https://github.com/micjamking/devtools-author/blob/master/app/styles/panel.scss#L119

I'll take a look in to it this evening (unless you beat me to it :wink: ).
