### ISSUE TITLE
Add ability to select font.

### ISSUE THREAD

**Issue by cowboy** [micjamking/devtools-author#71]
Is there any way to provide a font selection dropdown on the "Author Settings" page? That'd be superb!

**Comment by smlombardi** [comment]
Is there ANY way to change the font, as it is right now?

**Comment by micjamking** [comment]
Hey @cowboy & @smlombardi,

Currently font _selection_ in DevTools Author is agreeably poor, with the only way to manage the supported fonts is to use your desktop font manager tool, essentially enabling/disabling the system fonts based on the font-family stack cascade priority below:

[/app/styles/base/_variables.scss#L13](https://github.com/micjamking/devtools-author/blob/master/app/styles/base/_variables.scss#L13)
```scss
$mac-fonts: 'Hack', 'Source Code Pro', 'Droid Sans Mono', Monaco, Menlo, monospace;
$win-fonts: 'Hack', 'Source Code Pro', 'Droid Sans Mono', Consolas, Lucida Console, monospace;
$lin-fonts: 'Hack', 'Source Code Pro', 'Droid Sans Mono', dejavu sans mono, monospace;
```

Making font selection a drop-down will require a little bit of work as well as probably switching to grabbing fonts from a CDN, but totally possible and I'll try to tackle this next.

Thanks again for the feedback!

**Comment by cowboy** [comment]
What about allowing the user to type the name of the font into an input? You could pre-populate it with the default (and allow the user to revert to the default) along with showing a sample code preview with the font face, size, and the theme.

**Comment by smlombardi** [comment]
> What about allowing the user to type the name of the font into an input? You could pre-populate it with the default (and allow the user to revert to the default) along with showing a sample code preview with the font face, size, and the theme.

this is how Atom works, and it's fine.

**Comment by micjamking** [comment]
(Apologies for the low-res screenshot, but you get the point.)

![screen shot 2016-01-29 at 12 32 03 am](https://cloud.githubusercontent.com/assets/651702/12673322/2c022656-c620-11e5-8966-6ab87723b084.png)

Just hit enter to save the font (the "close and reopen devtools..." alert will appear).

**Comment by cowboy** [comment]
Work perfectly with `mplus-2m-regular`, thanks!

**Comment by smlombardi** [comment]
Works with `SourceCodePro-Regular` as well.  Thank  you.
