### ISSUE TITLE
Can't change theme when theme name wraps

### ISSUE THREAD

**Issue by mcrider** [micjamking/devtools-author#72]
The dropdown is obscured by the text and i can't click on it.  Solved by making the dev tools panel wider, but should probably be handled in code :)  Thanks for the extension!
<img width="886" alt="screen shot 2016-01-27 at 11 37 53 am" src="https://cloud.githubusercontent.com/assets/130554/12620518/97c1c432-c4ea-11e5-8a42-1f37568b5d07.png">

**Comment by jano23** [comment]
For the time being you can drag the left border and make the screen big enough so there is no name wrap. Then you can change themes again

**Comment by semparichyoung** [comment]
I'm open another Dev tools from color page for trying color.

And than, you can find <h1> and remove it to re-select your theme
