### ISSUE TITLE
Computed panel rows use the default colour

### ISSUE THREAD

**Issue by danielgamble** [micjamking/devtools-author#73]
This is using the Monokai theme: https://i.imgur.com/LlZiiVw.png

I think a color just needs to be added for a few of the themes that would style the background of the box model as well as the alternate rows :)

**Comment by micjamking** [comment]
@danielgamble Thank you for bringing this issue to my attention; it appears to be happening when the DevTools window is docked, ie. the computed panel styles take effect when the DevTools window is expanded. 

I'll address this ASAP.

**Comment by danielgamble** [comment]
Sweet, looking forward to a fix. Will just use a theme that is light instead of dark for now :)

**Comment by micjamking** [comment]
Just pushed this out in update v0.4.6; thanks again for the feedback @danielgamble!
