### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by jano23** [micjamking/devtools-author#79]
I have a series of screenshots that show missing UI elements in Chrome.  They do show up in Chrome Canary. I have screenshots of both Chrome and Chrome Canary for each example. I have the latest version of each.

Im this first one the icons notice the missing Select, Toggle Device Mode on the upper lefthand corner and then the missing Customize and control DevTools and Close icons on the upper right.
<img width="386" alt="chrome" src="https://cloud.githubusercontent.com/assets/759023/12632729/6e28e984-c517-11e5-926d-14951498c418.png">
<img width="394" alt="canary" src="https://cloud.githubusercontent.com/assets/759023/12632741/82961734-c517-11e5-853d-3db1b60c74c4.png">

In the next image notice the icons missing for New Style Rule, Toggle Element State and Toggle Animation Controls in the Filter section 

<img width="385" alt="chrome2" src="https://cloud.githubusercontent.com/assets/759023/12632799/e5c89f5c-c517-11e5-84c2-0989bdc9bbc1.png">

<img width="396" alt="canary2" src="https://cloud.githubusercontent.com/assets/759023/12632803/f0733444-c517-11e5-9735-c97fcd8798d1.png">

**Comment by jano23** [comment]
I didn't try ALL the themes but I did try several. In the images above I am using the Coda Theme

**Comment by dgurkaynak** [comment]
I have the same issue with Chrome 47.0.2526.111 (64-bit) running on OS X 10.11.3.

**Comment by micjamking** [comment]
Related #76
