### ISSUE TITLE
No DevTools Icons

### ISSUE THREAD

**Issue by artifactdev** [micjamking/devtools-author#82]
Hi, if I enable devtools author the devtools don't show the icons for menu or console errors. The Number of Errors aren't shown too.

**Comment by gladimdim** [comment]
I have the same issue.

MacOS 10.10.5. Chrome Version 47.0.2526.111 (64-bit).

No icons for buttons:
<img width="655" alt="screen shot 2016-01-28 at 10 25 52 am" src="https://cloud.githubusercontent.com/assets/448179/12638951/a04f8e30-c5a9-11e5-90e8-09e0a81afdaf.png">

**Comment by micjamking** [comment]
Related #76
