### ISSUE TITLE
Broken icons and unreadable text color

### ISSUE THREAD

**Issue by drfisher** [micjamking/devtools-author#83]
Icons are invisible (but clickable).
console.info has unreadable text color in a Monokai theme.

Mac OS El Capitan
Chrome 47.0.2526.111

<img width="639" alt="issue" src="https://cloud.githubusercontent.com/assets/530830/12643736/00567544-c5cf-11e5-9a68-a0ba89170518.png">

**Comment by micjamking** [comment]
Hi @drfisher, I just pushed out a release (v0.4.7: https://github.com/micjamking/devtools-author/commit/616a9e6dd37c2472b23cf49bb96a470897dd86c1) which resolves similar icon issues #76, #79, #82.

Can you confirm if v0.4.7 resolves this issue?

**Comment by drfisher** [comment]
@micjamking, the issue with icons was resolved. Thanks for your work!
<img width="643" alt="issue2" src="https://cloud.githubusercontent.com/assets/530830/12643945/7066796e-c5d0-11e5-8c36-17c216803703.png">

**Comment by micjamking** [comment]
Hey @drfisher 

I'm unable to replicate the console.info issues (see screenshot below):

![screen shot 2016-01-28 at 2 17 54 am](https://cloud.githubusercontent.com/assets/651702/12644216/6f471c2a-c565-11e5-82bf-ef026b30a506.png)

Are there any other environment details you can provide? I'm not very familiar with console.info, but it appears in your case the output is a string message (?). Is this the same experience with `console.log()`? Does this also occur when DevTools is detached?

Last (and this might be much to ask), but if you can detach the DevTools window and open a subsequent DevTools window on the first one (`cmd + opt + I`), you can use the element inspector from the second window to highlight the text in the first windows console. If you can determine the exact class name (or even better show a screenshot) of the text element being displayed, this would be _extremely_ helpful in pinpointing the issue. I understand if it's a bit much.

I appreciate the feedback!

**Comment by MWrathDev** [comment]
This has not been resolved for me styling is applied incorrectly to the floating menu on click. However im using the dev version of chrome, unsure if this is a priority for you.

https://www.chromium.org/getting-involved/dev-channel

As far as i know only affecting monokai, details:

MS windows 7 64bit
Chrome Version 49.0.2623.23 dev-m (64-bit)

**Comment by MWrathDev** [comment]
Just to clarify, what i mean is that the color is way too light and since the dropdown context menu is left with a white background, it's impossible to read text, unless you hover, as follows:

![dev-author](https://cloud.githubusercontent.com/assets/8978176/12652368/997e92aa-c63e-11e5-8c41-5d4a7fac0076.PNG)

After further investigation this happens in the following themes:

Atelier Dune
Base16
Bongozilla
Material Dark
Mocha (sort of)
Monokai
NodeJS
Railscast
Spacegray Eighties Dark (sort of)

**Comment by micjamking** [comment]
Hi @MWrathDev 

Thanks for the feedback!

Based on what you're experiencing in your comment https://github.com/micjamking/devtools-author/issues/83#issuecomment-176290250, this appears to be a distinct and separate issue from the missing icons and `console.info` output bugs specified in OP's issue.

Your issue also appears to be specific to Windows, as Mac (OSX 10.11.3) uses the system default styling for select menu pop-ups (see below):

**Chrome Canary v50.0.2633.0 (64-bit)**

![screen shot 2016-01-28 at 9 16 43 pm](https://cloud.githubusercontent.com/assets/651702/12669515/53553fe2-c605-11e5-8953-ea5aacbb83ab.png)

**Chrome v48.0.2564.97 (64-bit)**

![screen shot 2016-01-28 at 9 17 37 pm](https://cloud.githubusercontent.com/assets/651702/12669516/535be4f0-c605-11e5-8275-3fd062515085.png)

Once I resolve the `console.info` text color bug, I will close this issue. Do you mind creating a new issue for this (noting the Windows environment)?

**Comment by drfisher** [comment]
Hello @micjamking 

Sorry about wrong issue description. It was not a console.info. It was a console.time. To reproduce just paste this code in a console and press Enter

`console.time('test');setTimeout(()=>{console.timeEnd('test');}, 1000);`

<img width="561" alt="console_issue" src="https://cloud.githubusercontent.com/assets/530830/12694955/02c29d7c-c74f-11e5-91ea-fefa4fe75317.png">

**Comment by micjamking** [comment]
![screen shot 2016-01-30 at 7 26 32 pm](https://cloud.githubusercontent.com/assets/651702/12700496/98180742-c789-11e5-99d5-df7c91e5a031.png)

Resolved and released in v.0.5.1 https://github.com/micjamking/devtools-author/commit/ff176382ac8e35ca0ce1f09144132f5273a5dc06
