### ISSUE TITLE
"Reload DevTools"? 

### ISSUE THREAD

**Issue by thinkhuman** [micjamking/devtools-author#84]
The instructions say themes take effect after you "Reload DevTools". Do you mean close DevTools and open them again? I can't get a single theme to apply.

**Comment by jmeas** [comment]
@thinkhuman yes, that's what the instructions mean. Did you follow the rest of the installation instructions? There are at least 2 experimental flags that you need to flip on in 2 different places.

**Comment by thinkhuman** [comment]
I followed the 3-step instructions here: http://mikeking.io/devtools-author/

**Comment by MWrathDev** [comment]
Yes, chrome extensions run in their own instance isolated from that of the browser and can only interact with page / browser elements through a defined API. Thus it's always best to relaunch when first installing them.

As for the changing theme: make selection -> double tap f12, but concur the docs could use a little update :)

**Comment by micjamking** [comment]
Available in release v0.4.9 https://github.com/micjamking/devtools-author/commit/3d80a7a903c5248eaabba96ae60c83e81d67ae6f

**Comment by micjamking** [comment]
Hey @thinkhuman & @MWrathDev, my apologies for prematurely closing this issue without addressing both of your concerns: changing 'Reload' to 'Close and reopen' within the Author Settings panel itself and updating the documentation to include the necessary restart of Chrome after setting a flag. This is my oversight for assuming, but it _is_ a necessary step when changing any Chrome flags. 

The Chrome Store [description](https://chrome.google.com/webstore/detail/devtools-author/egfhcfdfnajldliefpdoaojgahefjhhi), [Usage](https://github.com/micjamking/devtools-author#usage) section of GitHub README.md and [Getting Setup](http://mikeking.io/devtools-author/#usage) section of the microsite have been updated accordingly. 
:v:
