### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by TheJaredWilcurt** [micjamking/devtools-author#85]
I'm on Windows and having a scrollbar is actually very useful, especially the up and down arrows on it. Currently all the themes I've tried have this tiny little 2 pixel wide, and often not much taller scrollbar that isn't even clickable. Seriously, what's the point if you can't use it. There is no clickable pixels, you either resize the sidbar or click on an element in the DOM.

![devtools-author](https://cloud.githubusercontent.com/assets/4629794/12660387/85f7ffc6-c5e1-11e5-8f0f-f7ede26b37fc.png)

Can we either an option to disable custom scrollbars and let the OS do what the OS do?

**Comment by micjamking** [comment]
Released in v0.4.11 https://github.com/micjamking/devtools-author/commit/2fc4c72a0471af29425d01cf648a87856c553278
