### ISSUE TITLE
Tabs above CSS on Elements pane don't overflow properly

### ISSUE THREAD

**Issue by prurph** [micjamking/devtools-author#88]
Great plugin! Slight visual issue with these tabs:

![devtools-author 2016-01-28 21-06-31](https://cloud.githubusercontent.com/assets/6109531/12665102/333c669c-c603-11e5-8bd4-04a6dd6336ee.png)

The normal devtools behavior is for these to always take up just one row.

They also appear to be just a bit too tall and are exceeding the bar there on the top.

**Comment by micjamking** [comment]
@prurph Thanks for pointing this out! I've definitely noticed this, but there's several pieces at play which sets the sizing of those tabs so it's a little tricky. Will address asap.

**Comment by micjamking** [comment]
This should be resolved in release v0.5.9; please let me know if you are still experiencing issues.

![screen shot 2016-02-03 at 1 02 27 am](https://cloud.githubusercontent.com/assets/651702/12780476/4f7e7c88-ca12-11e5-84d7-53ce3ab14483.png)
![screen shot 2016-02-03 at 1 02 41 am](https://cloud.githubusercontent.com/assets/651702/12780477/4f7f8290-ca12-11e5-9be8-524a6a22ae8e.png)
![screen shot 2016-02-03 at 1 02 56 am](https://cloud.githubusercontent.com/assets/651702/12780480/4f845130-ca12-11e5-93f3-e7e329c7dd9e.png)
![screen shot 2016-02-03 at 1 03 07 am](https://cloud.githubusercontent.com/assets/651702/12780478/4f8245de-ca12-11e5-81ef-641a3d0273e9.png)
