### ISSUE TITLE
.selected height is incorrect for smaller font sizes.

### ISSUE THREAD

**Issue by trevor-allen** [micjamking/devtools-author#91]
The height of selected rows in the Elements view is wonky at a small font-size [10px](https://i.imgur.com/ZhQmsvZ.png)

**Comment by micjamking** [comment]
Thanks for the feedback @trevor-allen 

![screen shot 2016-01-30 at 7 57 22 pm](https://cloud.githubusercontent.com/assets/651702/12700542/ea500e18-c78b-11e5-91f9-bf602edd179c.png)

This should be resolved in v0.5.3 19bb6b6
