### ISSUE TITLE
Some characters not visible when editing attribute values

### ISSUE THREAD

**Issue by pjconnors** [micjamking/devtools-author#92]
The `=` and `"` characters are not visible when I double click into an attribute to edit its value (eg. editing a class name.)

Example:
![image](https://cloud.githubusercontent.com/assets/3886376/12683431/39ea402a-c687-11e5-9b73-d80f61a6debb.png)
Selecting everything in that view shows that those characters are there, but their color is white.
![image](https://cloud.githubusercontent.com/assets/3886376/12683517/b9210ea0-c687-11e5-8b69-b582fa7c7cfb.png)

I have tested this with a few different themes, including the default 3024.

**Comment by micjamking** [comment]
Thanks for the feedback @pjconnors, will resolve asap!

**Comment by micjamking** [comment]
Resolved and released in v.0.5.2 https://github.com/micjamking/devtools-author/commit/58c43ceaed847cebd2df6993f196af0b7bf89a5f
