### ISSUE TITLE
Console errors on dark theme are in white 

### ISSUE THREAD

**Issue by abhi1-g** [micjamking/devtools-author#94]
Console error text on dark themes is in white with a background-color of light pink and so it isin't quite visible 
![c3](https://cloud.githubusercontent.com/assets/8082746/12710902/ee7b60fe-c8e0-11e5-8913-eed55c310640.JPG)

**Comment by DisasterMan78** [comment]
Confirmed occurring with Monokai theme. Also, elements logged to console do not have the same theming as in the elements panel, and legibility is very poor.

If you would prefer this be raised as a separate issue, let me know.

![image](https://cloud.githubusercontent.com/assets/2079401/12722997/5b9dc51e-c8ff-11e5-81da-7b2ca55bdcdc.png)

**Comment by micjamking** [comment]
@abhi1-g / @DisasterMan78 thanks for bringing this to my attention! This actually (partially) was a general styling issue, in the way that it affected multiple dark themes. However, this is resolved in v0.5.5 5ba3d18

![screen shot 2016-02-01 at 10 37 00 pm](https://cloud.githubusercontent.com/assets/651702/12743873/e5a20b14-c934-11e5-8747-e97ca904af44.png)

**Comment by DisasterMan78** [comment]
Quick tip to force update of extensions:

Go to chrome://extensions/
Check the 'Developer mode' checkbox
Click [Update extensions now]

**Comment by DisasterMan78** [comment]
Many thanks for the swift update.
Elements logged to console are still barely legible, I shall open a separate ticket for this.
