### ISSUE TITLE
Content of the toggle element state is overflowing 

### ISSUE THREAD

**Issue by abhi1-g** [micjamking/devtools-author#95]
The content of the Toggle Element State Toggle which has 4 checkboxes that force an element state is overflowing its container and is getting hidden

**Comment by micjamking** [comment]
Hi @abhi1-g thanks for bringing this to my attention! I'm pretty sure I know what you're talking about, but just so I can confirm the exact issue you are experiencing, do you mind providing a screenshot? This will also help me compare when I complete the fix.

**Comment by abhi1-g** [comment]
Sure 
![capture](https://cloud.githubusercontent.com/assets/8082746/12710807/210c0452-c8e0-11e5-8f99-92267b3de170.JPG)
![c1](https://cloud.githubusercontent.com/assets/8082746/12710809/25126938-c8e0-11e5-8c48-ef5881e75bfd.JPG)

**Comment by micjamking** [comment]
@abhi1-g this is resolved in v0.5.6 5a01068

![screen shot 2016-02-01 at 10 53 54 pm](https://cloud.githubusercontent.com/assets/651702/12744230/2239a10c-c937-11e5-8ba8-f8c272da7735.png)
