### ISSUE TITLE
Darcula

### ISSUE THREAD

**Issue by klimashkin** [micjamking/devtools-author#97]
I don't know if here a good place to request new theme.
Many developers work with Jetbrains Darcula theme in theirs Webstorm/phpstorm etc. Good to have it in devtools also!

![Darcula]
(https://pbs.twimg.com/media/CAh_g1BW4AAXFWU.png)

![Darcula]
(http://dazzet.co/wp-content/uploads/2014/09/02-darkula.png)

**Comment by micjamking** [comment]
@klimashkin here is a perfect place to request new themes! If you can locate the color palette (hex or RGB) I can try to recreate the theme. The match may not be perfect since Devtools itself has theming restrictions, but we can probably get pretty close.

**Comment by bolensmichael** [comment]
I think I found some hex values for the theme. I'm happy to take a stab at it!

**Comment by micjamking** [comment]
@bolensmichael go for it! Feel free to make a PR that references this issue (#97) when you're done.

**Comment by micjamking** [comment]
Awesome work by @bolensmichael! This is in release v0.5.7 c8d9064

![screen shot 2016-02-02 at 8 30 10 pm](https://cloud.githubusercontent.com/assets/651702/12776891/705964f0-c9fd-11e5-9933-af243e396e00.png)

**Comment by klimashkin** [comment]
To be honest it's not Darcula :) I made a screenshot. Left - JetBrains Darcula, right - this plugin.
All colors are different

![screen shot 2016-02-10 at 12 17 38 pm](https://cloud.githubusercontent.com/assets/576077/12960579/d096a244-cff0-11e5-8f1d-b0291e030dc8.png)

**Comment by micjamking** [comment]
@klimashkin I'm not sure where @bolensmichael found the color palette values for the theme, but it does appear the syntax highlighting itself is a bit off. I mentioned this in my original comment here: https://github.com/micjamking/devtools-author/issues/97#issuecomment-178452032, but something to note is that DevTools itself does have some theming restrictions which may prevent 100%, 1-to-1 mapping of the themes from another IDE.

The Darcula theme is available here: https://github.com/micjamking/devtools-author/blob/master/app/styles/themes/darcula.scss. Any additional styles needed to improve the syntax highlighting accuracy for a _specific_ theme can be added to the bottom of that theme file. If you'd like, you can contribute changes by following the [steps on the README](https://github.com/micjamking/devtools-author#contributing) and make a pull request.

:v:

**Comment by bolensmichael** [comment]
Hi @klimashkin sorry it's not exactly right. I was going based off of the images and color codes on the site here **http://eclipsecolorthemes.org/?view=theme&id=14569** since you didn't provide the hex scheme and matched it pretty much identically to what is displayed there. The groundwork for the theme is now merged in, so feel free to swap the colors in that you'd prefer them to be!
